// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"server_go/internal/handler"
	"server_go/internal/repository"
	"server_go/internal/server"
	"server_go/internal/service"
	"server_go/pkg/app"
	"server_go/pkg/jwt"
	"server_go/pkg/log"
	"server_go/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	serviceService := service.NewService(transaction, logger, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	adminRepository := repository.NewAdminRepository(repositoryRepository)
	adminService := service.NewAdminService(serviceService, adminRepository)
	adminHandler := handler.NewAdminHandler(handlerHandler, adminService)
	consumerRepository := repository.NewConsumerRepository(repositoryRepository)
	consumerService := service.NewConsumerService(serviceService, consumerRepository)
	consumerHandler := handler.NewConsumerHandler(handlerHandler, consumerService)
	articleRepository := repository.NewArticleRepository(repositoryRepository)
	tagRepository := repository.NewTagRepository(repositoryRepository)
	articleService := service.NewArticleService(serviceService, articleRepository, tagRepository)
	articleHandler := handler.NewArticleHandler(handlerHandler, articleService)
	tagService := service.NewTagService(serviceService, tagRepository)
	tagHandler := handler.NewTagHandler(handlerHandler, tagService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, adminHandler, consumerHandler, articleHandler, tagHandler)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewAdminRepository, repository.NewConsumerRepository, repository.NewTagRepository, repository.NewArticleRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewAdminService, service.NewConsumerService, service.NewTagService, service.NewArticleService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewAdminHandler, handler.NewConsumerHandler, handler.NewTagHandler, handler.NewArticleHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

// build App
func newApp(
	httpServer *http.Server,
) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("demo-server"))
}
